import {
    BookOpenText,
    Boxes,
    BriefcaseBusiness,
    CalendarDays,
    FolderKanban,
    FolderTree,
    Handshake,
    Package,
    Tags,
    Users,
    UsersRound,
} from 'lucide-react';
import type { ResourceConfig } from '@/types/admin';

export const resourceConfigs: Record<string, ResourceConfig> = {
    products: {
        key: 'products',
        title: 'Produk',
        singular: 'Produk',
        description: 'Kelola katalog produk digital dan fisik.',
        endpoint: '/api/products',
        icon: Package,
        columns: [
            { key: 'title', label: 'Produk' },
            { key: 'category.name', label: 'Kategori' },
            { key: 'type', label: 'Tipe', type: 'status' },
            { key: 'status', label: 'Status', type: 'status' },
            { key: 'price', label: 'Harga', type: 'currency' },
            { key: 'stock', label: 'Stok' },
        ],
        fields: [
            { key: 'title', label: 'Judul', type: 'text', required: true, placeholder: 'Nama produk' },
            {
                key: 'category_id', label: 'Kategori', type: 'relation', relationUrl: '/api/product-categories',
                relationLabel: 'name', source: 'category.id',
            },
            {
                key: 'image_id', label: 'Gambar produk', type: 'media', source: 'image.id',
                previewSource: 'image.url', mediaPurpose: 'products', fullWidth: true,
            },
            {
                key: 'type', label: 'Tipe', type: 'select', required: true,
                options: [{ label: 'Digital', value: 'digital' }, { label: 'Fisik', value: 'physical' }],
            },
            {
                key: 'status', label: 'Status', type: 'select', required: true,
                options: [{ label: 'Aktif', value: 'active' }, { label: 'Nonaktif', value: 'inactive' }],
            },
            { key: 'short_description', label: 'Deskripsi singkat', type: 'textarea', fullWidth: true },
            { key: 'description', label: 'Deskripsi lengkap', type: 'textarea', fullWidth: true },
            { key: 'price', label: 'Harga', type: 'number' },
            { key: 'stock', label: 'Stok', type: 'number' },
            { key: 'digital_file_url', label: 'URL berkas digital', type: 'text', fullWidth: true },
            { key: 'is_featured', label: 'Produk unggulan', type: 'boolean' },
            { key: 'is_best_seller', label: 'Produk terlaris', type: 'boolean' },
        ],
        searchKeys: ['title', 'slug', 'category.name', 'type', 'status'],
    },
    'product-categories': {
        key: 'product-categories',
        title: 'Kategori Produk',
        singular: 'Kategori Produk',
        description: 'Atur kelompok dan urutan katalog produk.',
        endpoint: '/api/product-categories',
        icon: Boxes,
        columns: [
            { key: 'name', label: 'Nama' },
            { key: 'slug', label: 'Slug' },
            { key: 'sort_order', label: 'Urutan' },
            { key: 'updated_at', label: 'Diperbarui', type: 'date' },
        ],
        fields: [
            { key: 'name', label: 'Nama', type: 'text', required: true },
            { key: 'sort_order', label: 'Urutan', type: 'number' },
        ],
        searchKeys: ['name', 'slug'],
    },
    services: {
        key: 'services',
        title: 'Layanan',
        singular: 'Layanan',
        description: 'Kelola layanan utama yang ditampilkan ke publik.',
        endpoint: '/api/services',
        icon: BriefcaseBusiness,
        columns: [
            { key: 'title', label: 'Layanan' },
            { key: 'category.name', label: 'Kategori' },
            { key: 'is_active', label: 'Aktif', type: 'boolean' },
            { key: 'is_featured', label: 'Unggulan', type: 'boolean' },
            { key: 'sort_order', label: 'Urutan' },
        ],
        fields: [
            { key: 'title', label: 'Judul', type: 'text', required: true },
            {
                key: 'category_id', label: 'Kategori', type: 'relation', relationUrl: '/api/service-categories',
                relationLabel: 'name', source: 'category.id',
            },
            {
                key: 'icon_id', label: 'Ikon layanan', type: 'media', source: 'icon.id',
                previewSource: 'icon.url', mediaPurpose: 'services', fullWidth: true,
            },
            { key: 'short_description', label: 'Deskripsi singkat', type: 'textarea', fullWidth: true },
            { key: 'description', label: 'Deskripsi lengkap', type: 'textarea', fullWidth: true },
            { key: 'sort_order', label: 'Urutan', type: 'number' },
            { key: 'is_active', label: 'Aktif', type: 'boolean' },
            { key: 'is_featured', label: 'Unggulan', type: 'boolean' },
        ],
        searchKeys: ['title', 'slug', 'category.name'],
    },
    'service-categories': {
        key: 'service-categories',
        title: 'Kategori Layanan',
        singular: 'Kategori Layanan',
        description: 'Atur kelompok dan urutan layanan.',
        endpoint: '/api/service-categories',
        icon: FolderTree,
        columns: [
            { key: 'name', label: 'Nama' },
            { key: 'slug', label: 'Slug' },
            { key: 'sort_order', label: 'Urutan' },
            { key: 'updated_at', label: 'Diperbarui', type: 'date' },
        ],
        fields: [
            { key: 'name', label: 'Nama', type: 'text', required: true },
            { key: 'sort_order', label: 'Urutan', type: 'number' },
        ],
        searchKeys: ['name', 'slug'],
    },
    clients: {
        key: 'clients',
        title: 'Klien & Partner',
        singular: 'Klien',
        description: 'Kelola organisasi kolaborator dan media partner.',
        endpoint: '/api/clients',
        icon: Handshake,
        columns: [
            { key: 'name', label: 'Nama' },
            { key: 'type', label: 'Jenis', type: 'status' },
            { key: 'website_url', label: 'Website' },
            { key: 'is_featured', label: 'Unggulan', type: 'boolean' },
            { key: 'sort_order', label: 'Urutan' },
        ],
        fields: [
            { key: 'name', label: 'Nama', type: 'text', required: true },
            {
                key: 'type', label: 'Jenis kolaborasi', type: 'select', required: true,
                options: [
                    { label: 'Case Collaboration', value: 'CASE_COLLABORATION' },
                    { label: 'Event Collaboration', value: 'EVENT_COLLABORATION' },
                    { label: 'Media Partner', value: 'MEDIA_PARTNER' },
                ],
            },
            {
                key: 'logo_id', label: 'Logo klien', type: 'media', source: 'logo.id',
                previewSource: 'logo.url', mediaPurpose: 'clients', fullWidth: true,
            },
            { key: 'website_url', label: 'URL Website', type: 'text' },
            { key: 'sort_order', label: 'Urutan', type: 'number' },
            { key: 'is_featured', label: 'Unggulan', type: 'boolean' },
        ],
        searchKeys: ['name', 'slug', 'type', 'website_url'],
    },
    articles: {
        key: 'articles',
        title: 'Artikel',
        singular: 'Artikel',
        description: 'Kelola draft, publikasi, dan arsip artikel.',
        endpoint: '/api/articles',
        icon: BookOpenText,
        columns: [
            { key: 'title', label: 'Judul' },
            { key: 'category.name', label: 'Kategori' },
            { key: 'status', label: 'Status', type: 'status' },
            { key: 'published_at', label: 'Terbit', type: 'date' },
            { key: 'updated_at', label: 'Diperbarui', type: 'date' },
        ],
        fields: [
            { key: 'title', label: 'Judul', type: 'text', required: true },
            {
                key: 'category_id', label: 'Kategori', type: 'relation', relationUrl: '/api/article-categories',
                relationLabel: 'name', source: 'category.id',
            },
            {
                key: 'thumbnail_id', label: 'Thumbnail artikel', type: 'media', source: 'thumbnail.id',
                previewSource: 'thumbnail.url', mediaPurpose: 'articles', fullWidth: true,
            },
            { key: 'excerpt', label: 'Ringkasan', type: 'textarea', fullWidth: true },
            { key: 'content', label: 'Isi artikel', type: 'richtext', required: true, fullWidth: true },
            {
                key: 'status', label: 'Status', type: 'select', required: true,
                options: [
                    { label: 'Draft', value: 'draft' },
                    { label: 'Terbit', value: 'published' },
                    { label: 'Arsip', value: 'archived' },
                ],
            },
            { key: 'published_at', label: 'Waktu terbit', type: 'datetime-local' },
        ],
        searchKeys: ['title', 'slug', 'category.name', 'status'],
    },
    'article-categories': {
        key: 'article-categories',
        title: 'Kategori Artikel',
        singular: 'Kategori Artikel',
        description: 'Atur pengelompokan konten artikel.',
        endpoint: '/api/article-categories',
        icon: Tags,
        columns: [
            { key: 'name', label: 'Nama' },
            { key: 'slug', label: 'Slug' },
            { key: 'updated_at', label: 'Diperbarui', type: 'date' },
        ],
        fields: [
            { key: 'name', label: 'Nama', type: 'text', required: true },
        ],
        searchKeys: ['name', 'slug'],
    },
    users: {
        key: 'users',
        title: 'Pengguna',
        singular: 'Pengguna',
        description: 'Kelola akun yang dapat mengakses sistem.',
        endpoint: '/api/admin/users',
        icon: Users,
        columns: [
            { key: 'name', label: 'Nama' },
            { key: 'username', label: 'Username' },
            { key: 'email', label: 'Email' },
            { key: 'role', label: 'Role', type: 'status' },
            { key: 'created_at', label: 'Dibuat', type: 'date' },
        ],
        fields: [
            { key: 'name', label: 'Nama lengkap', type: 'text', required: true },
            { key: 'username', label: 'Username', type: 'text', required: true, placeholder: 'nama-pengguna' },
            { key: 'email', label: 'Email', type: 'text', required: true, placeholder: 'nama@example.com' },
            {
                key: 'role', label: 'Role', type: 'select', required: true,
                options: [{ label: 'Administrator', value: 'admin' }, { label: 'User', value: 'user' }],
            },
            {
                key: 'password', label: 'Password', type: 'password', required: true,
                optionalOnEdit: true, fullWidth: true, placeholder: 'Minimal 8 karakter',
            },
        ],
        searchKeys: ['name', 'username', 'email', 'role'],
    },
    'team-members': {
        key: 'team-members',
        title: 'Tim',
        singular: 'Anggota Tim',
        description: 'Kelola anggota tim 180DC UNAIR.',
        endpoint: '/api/team-members',
        icon: UsersRound,
        columns: [
            { key: 'name', label: 'Nama' },
            { key: 'slug', label: 'Slug' },
            { key: 'email', label: 'Email' },
            { key: 'is_active', label: 'Aktif', type: 'boolean' },
            { key: 'created_at', label: 'Dibuat', type: 'date' },
        ],
        fields: [
            { key: 'name', label: 'Nama', type: 'text', required: true, placeholder: 'Nama lengkap' },
            { key: 'slug', label: 'Slug', type: 'text', required: true, placeholder: 'nama-slug-unik' },
            {
                key: 'image_id', label: 'Foto', type: 'media', source: 'image.id',
                previewSource: 'image.url', mediaPurpose: 'general', fullWidth: true,
            },
            { key: 'email', label: 'Email', type: 'text', placeholder: 'email@example.com' },
            { key: 'linkedin_url', label: 'LinkedIn URL', type: 'text', placeholder: 'https://linkedin.com/in/...' },
            { key: 'instagram_url', label: 'Instagram URL', type: 'text', placeholder: 'https://instagram.com/...' },
            { key: 'bio', label: 'Bio', type: 'textarea', fullWidth: true },
            { key: 'is_active', label: 'Aktif', type: 'boolean' },
        ],
        searchKeys: ['name', 'slug', 'email', 'bio'],
    },
    'event-categories': {
        key: 'event-categories',
        title: 'Kategori Event',
        singular: 'Kategori Event',
        description: 'Atur pengelompokan event.',
        endpoint: '/api/event-categories',
        icon: FolderKanban,
        columns: [
            { key: 'name', label: 'Nama' },
            { key: 'slug', label: 'Slug' },
            { key: 'events_count', label: 'Jumlah Event' },
            { key: 'updated_at', label: 'Diperbarui', type: 'date' },
        ],
        fields: [
            { key: 'name', label: 'Nama', type: 'text', required: true },
            { key: 'slug', label: 'Slug', type: 'text', required: true },
        ],
        searchKeys: ['name', 'slug'],
    },
    events: {
        key: 'events',
        title: 'Event',
        singular: 'Event',
        description: 'Kelola event, jadwal, dan registrasi.',
        endpoint: '/api/events',
        icon: CalendarDays,
        columns: [
            { key: 'title', label: 'Judul' },
            { key: 'category.name', label: 'Kategori' },
            { key: 'status', label: 'Status', type: 'status' },
            { key: 'is_featured', label: 'Unggulan', type: 'boolean' },
            { key: 'is_paid', label: 'Berbayar', type: 'boolean' },
            { key: 'start_at', label: 'Mulai', type: 'date' },
        ],
        fields: [
            { key: 'title', label: 'Judul', type: 'text', required: true },
            { key: 'slug', label: 'Slug', type: 'text', required: true },
            {
                key: 'category_id', label: 'Kategori', type: 'relation', relationUrl: '/api/event-categories',
                relationLabel: 'name', source: 'category.id',
            },
            {
                key: 'image_id', label: 'Gambar event', type: 'media', source: 'image.id',
                previewSource: 'image.url', mediaPurpose: 'general', fullWidth: true,
            },
            { key: 'description', label: 'Deskripsi', type: 'textarea', fullWidth: true },
            { key: 'location', label: 'Lokasi', type: 'text' },
            { key: 'start_at', label: 'Waktu mulai', type: 'datetime-local' },
            { key: 'end_at', label: 'Waktu selesai', type: 'datetime-local' },
            { key: 'gdoc_url', label: 'GDoc URL', type: 'text' },
            {
                key: 'status', label: 'Status', type: 'select', required: true,
                options: [
                    { label: 'Aktif', value: 'active' },
                    { label: 'Nonaktif', value: 'inactive' },
                    { label: 'Draft', value: 'draft' },
                ],
            },
            { key: 'price', label: 'Harga', type: 'number' },
            { key: 'is_paid', label: 'Berbayar', type: 'boolean' },
            { key: 'is_featured', label: 'Unggulan', type: 'boolean' },
        ],
        searchKeys: ['title', 'slug', 'category.name', 'status', 'location'],
    },
};

export function getResourceConfig(key: string): ResourceConfig | undefined {
    return resourceConfigs[key];
}
