info:
  name: Local

variables:
  - name: base_url
    value: http://localhost:8080/api
    secret: false
  - name: token
    value: ""
    secret: false
  - name: team_member_id
    value: ""
    secret: false
  - name: product_id
    value: ""
    secret: false
  - name: cart_item_id
    value: ""
    secret: false
